DELETE FROM [Lnd].[People]
DELETE FROM [Lnd].[Returns]
DELETE FROM [Lnd].[Superstore]

DELETE FROM [Stg].[People]
DELETE FROM [Stg].[Returns]
DELETE FROM [Stg].[Superstore]

DELETE FROM [Rpr].[FactSuperstore]
DELETE FROM [Rpr].[Region]
DELETE FROM [Rpr].[Category]
DELETE FROM [Rpr].[City]
DELETE FROM [Rpr].[Country]
DELETE FROM [Rpr].[Customer]
DELETE FROM [Rpr].[Order]
DELETE FROM [Rpr].[People]
DELETE FROM [Rpr].[Product]
DELETE FROM [Rpr].[Segment]
DELETE FROM [Rpr].[Ship]
DELETE FROM [Rpr].[State]
DELETE FROM [Rpr].[Subcategory]
