SELECT * FROM [Lnd].[People]
SELECT * FROM [Lnd].[Returns]
SELECT * FROM [Lnd].[Superstore]

SELECT * FROM [Stg].[People]
SELECT * FROM [Stg].[Returns]
SELECT * FROM [Stg].[Superstore]

SELECT * FROM [Rpr].[Category]
SELECT * FROM [Rpr].[City]
SELECT * FROM [Rpr].[Country]
SELECT * FROM [Rpr].[Customer]
SELECT * FROM [Rpr].[Order]
SELECT * FROM [Rpr].[People]
SELECT * FROM [Rpr].[Product]
SELECT * FROM [Rpr].[Region]
SELECT * FROM [Rpr].[Segment]
SELECT * FROM [Rpr].[Ship]
SELECT * FROM [Rpr].[State]
SELECT * FROM [Rpr].[Subcategory]
SELECT * FROM [Rpr].[FactSuperstore]